CREATE TABLE usrs
(
    id         bigint generated by default as identity constraint usr_pkey PRIMARY KEY,
    username   varchar(255),
    password   varchar(255),
    email      varchar(60),
    active     boolean not null ,
    blocked    boolean not null ,
    created_at timestamp
);

CREATE TABLE permissions
(
    id   bigint generated by default as identity constraint permissions_pkey PRIMARY KEY,
    name varchar
);

CREATE TABLE groups
(
    id   bigint generated by default as identity constraint groups_pkey PRIMARY KEY,
    name varchar
);

CREATE TABLE group_permission
(
    group_id      bigint not null,
    permission_id bigint not null,

    CONSTRAINT fk_group_permission_group_id FOREIGN KEY ("group_id") REFERENCES groups ("id"),
    CONSTRAINT fk_group_permission_permission_id FOREIGN KEY ("permission_id") REFERENCES permissions ("id"),
    CONSTRAINT group_permission_pkey PRIMARY KEY (group_id, permission_id)
);

CREATE TABLE user_permission
(
    user_id       bigint not null,
    permission_id bigint not null,

    CONSTRAINT fk_user_permission_user_id FOREIGN KEY ("user_id") REFERENCES usrs ("id"),
    CONSTRAINT fk_user_permission_permission_id FOREIGN KEY ("permission_id") REFERENCES permissions ("id"),
    CONSTRAINT user_permission_pkey PRIMARY KEY (user_id, permission_id)
);

CREATE TABLE user_group
(
    user_id  bigint not null,
    group_id bigint not null,

    CONSTRAINT fk_user_group_user_id FOREIGN KEY ("user_id") REFERENCES usrs ("id"),
    CONSTRAINT fk_user_group_group_id FOREIGN KEY ("group_id") REFERENCES groups ("id"),
    CONSTRAINT user_group_pkey PRIMARY KEY (user_id, group_id)
);
